# Used in HTML templates and titles
SiteTitle="demoflounder"

# Include port if running locally
Host="localhost:8165"

# Set this depending on whether you want to run this service standalone or through a reverse proxy server
HttpPort=8165
HttpsEnabled=false

# Folder containing subfolders for each user's files
# Must be absolute path due to bug
FilesDirectory="/home/alex/dev/go-flounder/files"
LogFile="./flounder.log"

# Gemini autogenerates self-signed certs
GeminiCertStore="/tmp"

# A wildcard TLS cert for HTTPS.
# Only required if HttpsEnabled=true
# TLSCertFile="./server.crt"
# TLSKeyFile="./server.key"

# Optional SMTP -- to send notification emails to users on acct activation
# SMTPServer = mail.goodsite.com:587
# SMTPUsername = myemail@coolplace.com
# SMTPPassword = hunter2

# Templates and static files
# Everything in the static subfolder will be served at /
TemplatesDirectory="./templates"
DBFile="./flounder.db"

MaxFileBytes=128000 # 128 KB
MaxUserBytes=10000000 # 10 MB

OkExtensions=[".gmi", ".txt", ".jpg", ".jpeg", ".gif", ".png", ".svg", ".webp", ".midi", ".json", ".csv", ".gemini", ".mp3", ".css", ".ttf", ".otf", ".woff", ".woff2"]

