# Used in HTML templates and titles
SiteTitle="demoflounder"

# Port to run server on
HttpPort=8165

# Include port if running locally
Host="flounder.local:8165"
# Running through reverse proxy
# Host="flounder.local" 

# Folder containing subfolders for each user's files
FilesDirectory="./files"
LogFile="./flounder.log"

# Gemini autogenerates self-signed certs
GeminiCertStore="/tmp"

# Optional SMTP -- to send notification emails to users on acct activation
# SMTPServer = mail.goodsite.com:587
# SMTPUsername = myemail@coolplace.com
# SMTPPassword = hunter2

# Whether to enable user SFTP access 
# experimental feature, enable at your own risk
EnableSFTP=true

# Templates and static files
# Everything in the static subfolder will be served at /
TemplatesDirectory="./templates"
DBFile="./flounder.db"

MaxFileBytes=128000 # 128 KB
MaxUserBytes=10000000 # 10 MB
MaxFilesPerUser=1024

OkExtensions=[".gmi", ".txt", ".jpg", ".jpeg", ".gif", ".png", ".svg", ".webp", ".midi", ".json", ".csv", ".gemini", ".mp3", ".css", ".ttf", ".otf", ".woff", ".woff2", ""]
