# Used in HTML templates and titles
SiteTitle="🐟flounder"

# Include port if != 443
Host="localhost:8443"

# Folder containing subfolders for each user's files
FilesDirectory="./files"
LogFile="./flounder.log"

# A wildcard TLS cert
TLSCertFile="./server.crt"
TLSKeyFile="./server.key"

# Templates and static files
# Everything in the static subfolder will be served at /
TemplatesDirectory="./templates"
DBFile="./flounder.db"

MaxFileSize=128000 # 128 KB
OkExtensions=["", ".gmi", ".txt", ".jpg", ".jpeg", ".gif", ".png", ".svg", ".webp", ".midi", ".json", ".csv", ".gemini", ".mp3", ".css", ".ttf", ".otf", ".woff", ".woff2"]

