# Used in HTML templates and titles
SiteTitle="🐟flounder"
RootDomain="localhost"
FilesDirectory="./files"
# handles templates and static files
# everything in the static subfolder will be served at root
TemplatesDirectory="./templates"
DBFile="./flounder.db"
MaxFileSize=1000000 # 1 MB
OkExtensions=[".gmi", ".txt", ".jpg", ".jpeg", ".gif", ".png", ".svg", ".webp", ".midi", ".json", ".csv", ".gemini", ".mp3", ".css", ".ttf", ".otf", ".woff", ".woff2"]

# log file
